### ISSUE TITLE
Is there has any code about Open Pattern Learning?

### ISSUE THREAD

**Issue by wpf5511** [knowitall/ollie#29]
I  want to do some research about the ollie.

I read the paper and I am interested in the part of open pattern learning.

And I want to now how to deduct pattern and template from lots of paths,you know a lot of details here

I review the code but not found the code,cause you already offer a model contains template and pattern,I am wondering whether you have the code and can you sharing it?

Thanks a lot !!

**Comment by schmmd** [comment]
The code is available and is located here: https://github.com/knowitall/ollie/tree/master/core/src/main/scala/edu/knowitall/openparse
