### ISSUE TITLE
Build fails with Java 1.8.0_92-b14, Mac Sierra

### ISSUE THREAD

**Issue by coolrb** [knowitall/ollie#32]
I am trying to build with Java 1.8.0_92-b14. However, it generates following error

> [ERROR] error: error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
[INFO] (bad constant pool tag 18 at byte 10)

>

**Comment by schmmd** [comment]
Ollie was built with Scala 2.9 so it requires Java 1.7.

**Comment by schmmd** [comment]
You can now run Ollie using Docker.

```
docker run -it schmmd/ollie:latest
```
