### ISSUE TITLE
Compile Error in JavaOllieWrapper.java

### ISSUE THREAD

**Issue by menuka94** [knowitall/ollie#33]
[Line 26 of JavaOllieWrapper.java](https://github.com/knowitall/ollie/blob/master/example/src/main/java/example/JavaOllieWrapper.java#L26) fails to compile.
`Cannot Resolve Constructor 'MaltParser(java.net.URL, scala.Option<java.io.File>)'`

**Comment by schmmd** [comment]
How are you compiling it?  Can you give the exact command?

**Comment by menuka94** [comment]
I'm building with Maven. `mvn clean compile`

**Comment by schmmd** [comment]
It builds fine in the Docker container at the latest SHA.  I'm not sure why you are having trouble compiling on your local machine.

**Comment by schmmd** [comment]
Perhaps you have Java 8 on your local machine and maven is failing to compile the scala sources, so this line fails as it cannot find the reference scala class.

**Comment by menuka94** [comment]
I set the Java compiler version to 1.7 and installed Scala 2.9.2.
However, I get the following output on running `mvn clean package`

>menuka@menuka:ollie(master)$ mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.washington.cs.knowitall.ollie:ollie-core_2.9.2:jar:1.0.4-SNAPSHOT
[WARNING] 'parent.relativePath' of POM edu.washington.cs.knowitall.ollie:ollie-core_2.9.2:1.0.4-SNAPSHOT (ollie/core/pom.xml) points at edu.washington.cs.knowitall.ollie:ollie instead of edu.washington.cs.knowitall:knowitall-oss, please verify your project structure @ line 4, column 11
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.washington.cs.knowitall.ollie:ollie-app:jar:1.0.1-SNAPSHOT
[WARNING] 'parent.relativePath' of POM edu.washington.cs.knowitall.ollie:ollie-app:1.0.1-SNAPSHOT (ollie/app/pom.xml) points at edu.washington.cs.knowitall.ollie:ollie instead of edu.washington.cs.knowitall:knowitall-oss, please verify your project structure @ line 8, column 11
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ollie-core
[INFO] ollie-app
[INFO] ollie
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ollie-core 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ollie-core_2.9.2 ---
[INFO] Deleting ollie/core/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ ollie-core_2.9.2 ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ollie-core_2.9.2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ ollie-core_2.9.2 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.1.1:compile (default) @ ollie-core_2.9.2 ---
[INFO] ollie/core/src/main/scala:-1: info: compiling
[INFO] Compiling 36 source files to ollie/core/target/classes at 1524145065410
[ERROR] error: error while loading CharSequence, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
[INFO] (bad constant pool tag 18 at byte 10)
[ERROR] error: error while loading Comparator, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/util/Comparator.class)' is broken
[INFO] (bad constant pool tag 18 at byte 20)
[ERROR] error: error while loading AnnotatedElement, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
[INFO] (bad constant pool tag 18 at byte 76)
[ERROR] error: error while loading Pattern, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/util/regex/Pattern.class)' is broken
[INFO] (bad constant pool tag 18 at byte 1750)
[ERROR] ollie/core/src/main/scala/edu/knowitall/ollie/OllieExtractionInstance.scala:37: error: value matcher is not a member of java.util.regex.Pattern
[ERROR]     passivePatternRegex.pattern.matcher(pat.pattern.serialize).matches() && (extr.rel.text.endsWith(" by"))
[ERROR]                                 ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/ollie/OllieExtractionInstance.scala:49: error: value matcher is not a member of java.util.regex.Pattern
[ERROR]     activePatternRegex.pattern.matcher(pat.pattern.serialize).matches()
[ERROR]                                ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/ollie/confidence/OllieFeatureSet.scala:36: error: overloaded method value replaceAllIn with alternatives:
[ERROR]   (target: java.lang.CharSequence,replacer: scala.util.matching.Regex.Match => String)String <and>
[ERROR]   (target: java.lang.CharSequence,replacement: String)String
[ERROR]  cannot be applied to (String, java.lang.String)
[ERROR]       val trimmed = leadingBe.replaceAllIn(trailingPrep.replaceAllIn(inst.extr.rel.text, ""), "")
[ERROR]                                                         ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/BuildPatterns.scala:57: error: type mismatch;
[ERROR]  found   : String
[ERROR]  required: java.lang.CharSequence
[ERROR]      graph.nodes.exists(node => "(?i)^VB".r.findFirstIn(node.postag).isDefined)
[INFO]                                                              ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/bootstrap/FindCommon.scala:19: error: value matcher is not a member of java.util.regex.Pattern
[ERROR]     part.filter { case (pos, tok, lem) => !target.pattern.matcher(pos).matches}
[ERROR]                                                           ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/bootstrap/FindTargetExtractions.scala:100: error: value mkString is not a member of Any
[ERROR]           val relcleanLemmaString = relcleanLemmas.mkString(" ")
[ERROR]                                                    ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/eval/RankPatterns.scala:41: error: could not find implicit value for parameter num: Numeric[Int]
[ERROR]         val yld = scoreds.map(scored => if (scored.score.getOrElse(throw new IllegalArgumentException("unscored extraction: " + scored))) 1 else 0).sum
[ERROR]                                                                                                                                                     ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/eval/RankPatterns.scala:52: error: diverging implicit expansion for type scala.math.Ordering[B]
[ERROR] starting with method Tuple2 in object Ordering
[ERROR]       for ((pattern, (p, y)) <- grouped.toSeq.sortBy(_._2).reverse) {
[ERROR]                                                     ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/eval/StatisticalSignificance.scala:59: error: could not find implicit value for parameter num: Numeric[Double]
[ERROR]     val average = differences.sum / differences.size.toDouble
[ERROR]                               ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/eval/StatisticalSignificance.scala:61: error: value >= is not a member of Nothing
[ERROR]     val pscore = normed.count(_ >= difference).toDouble / normed.size.toDouble
[ERROR]                                 ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/extract/TemplateExtractor.scala:123: error: type mismatch;
[ERROR]  found   : String
[ERROR]  required: java.lang.CharSequence
[ERROR]     var rel = group.replaceAllIn(template, (gm: Regex.Match) => matchGroup(gm.group(1))
[ERROR]                                  ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/extract/TemplateExtractor.scala:44: error: type mismatch;
[ERROR]  found   : java.lang.String
[ERROR]  required: java.lang.CharSequence
[ERROR]     val trailingPrep = TemplateExtractor.trailingPreposition.findFirstIn(template.serialize)
[ERROR]                                                                                   ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/template/BuildTemplates.scala:323: error: could not find implicit value for parameter num: Numeric[Int]
[ERROR]       assume(result.values.iterator.map(_.count).sum == histogram.iterator.map(_._2.count).sum)
[ERROR]                                                  ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/template/BuildTemplates.scala:361: error: could not find implicit value for parameter num: Numeric[Int]
[ERROR]         assume(result.values.iterator.map(_.count).sum == histogram.iterator.map(_._2.count).sum)
[ERROR]                                                    ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/template/BuildTemplates.scala:411: error: could not find implicit value for parameter num: Numeric[Int]
[ERROR]     logger.info((histogram.values.iterator.map(_.count).sum - filtered.values.iterator.map(_.count).sum).toString + " items removed.")
[ERROR]                                                         ^
[ERROR] ollie/core/src/main/scala/edu/knowitall/openparse/template/GeneralizeTemplate.scala:88: error: could not find implicit value for parameter num: Numeric[Double]
[ERROR]             if (overlaps.iterator.map(_._2).sum > 0.75) {
[ERROR]                                             ^
[ERROR] 20 errors found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ollie-core ......................................... FAILURE [ 10.754 s]
[INFO] ollie-app .......................................... SKIPPED
[INFO] ollie .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.883 s
[INFO] Finished at: 2018-04-19T19:07:54+05:30
[INFO] Final Memory: 15M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.1:compile (default) on project ollie-core_2.9.2: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by schmmd** [comment]
It looks to me that you're still getting errors from Java 8.  See the second line.

```
[INFO] Compiling 36 source files to ollie/core/target/classes at 1524145065410
[ERROR] error: error while loading CharSequence, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
```
